## Matrix transpose

In [9]:
import numpy as np

# first row of the matrix
horizontalVector = np.array([[1, 2, 3]])
print("Tpye of horizontal vector:", type(horizontalVector))

print("Horizontal vector:\n", horizontalVector)
print("Horizontal vector shape:", horizontalVector.shape)
print()

# transpose the vector
verticalVector = horizontalVector.T
print("Vertical vector:\n", verticalVector)
print("Vertical vector shape:", verticalVector.shape)
print()

# for a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Type of matrix:", type(matrix))
print("Matrix:\n", matrix)
print("Matrix shape:", matrix.shape)
print()

# transpose the matrix
transposedMatrix = matrix.T
print("Transposed matrix:\n", transposedMatrix)
print("Transposed matrix shape:", transposedMatrix.shape)
print()


Tpye of horizontal vector: <class 'numpy.ndarray'>
Horizontal vector:
 [[1 2 3]]
Horizontal vector shape: (1, 3)

Vertical vector:
 [[1]
 [2]
 [3]]
Vertical vector shape: (3, 1)

Type of matrix: <class 'numpy.ndarray'>
Matrix:
 [[1 2 3]
 [4 5 6]]
Matrix shape: (2, 3)

Transposed matrix:
 [[1 4]
 [2 5]
 [3 6]]
Transposed matrix shape: (3, 2)



With PyTorch it is exactly the same

In [8]:
import torch

# first row of the matrix - here using torch and tensor
horizontalTorchVector = torch.tensor([[1, 2, 3]])
print("Tpye of horizontal vector:", type(horizontalTorchVector))

print("Horizontal torch vector:\n", horizontalTorchVector)
print("Horizontal torch vector shape:", horizontalTorchVector.shape)
print()

# transpose the vector
verticalTorchVector = horizontalTorchVector.T
print("Vertical torch vector:\n", verticalTorchVector)
print("Vertical torch vector shape:", verticalTorchVector.shape)
print()

# for a matrix
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Type of matrix:", type(matrix))
print("Matrix:\n", matrix)
print("Matrix shape:", matrix.shape)
print()

# transpose the matrix
transposedMatrix = matrix.T
print("Transposed matrix:\n", transposedMatrix)
print("Transposed matrix shape:", transposedMatrix.shape)
print()


Tpye of horizontal vector: <class 'torch.Tensor'>
Horizontal torch vector:
 tensor([[1, 2, 3]])
Horizontal torch vector shape: torch.Size([1, 3])

Vertical torch vector:
 tensor([[1],
        [2],
        [3]])
Vertical torch vector shape: torch.Size([3, 1])

Type of matrix: <class 'torch.Tensor'>
Matrix:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Matrix shape: torch.Size([2, 3])

Transposed matrix:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])
Transposed matrix shape: torch.Size([3, 2])

