## Matrix Multiplication

Multiplying matrices is essentially calculating the dot product multiple times. However, there are some rules to consider when multiplying matrices:

- Matrices can only be multiplied if the number of columns in the first matrix is equal to the number of rows in the second matrix.
- In Python, matrix multiplication is performed using the `@` symbol.


In [10]:
import numpy as np

# Create a random matrix
matrixM = np.random.rand(3, 4)
matrixN = np.random.rand(4, 4)

result = np.round(matrixM @ matrixN, 3)
print(np.round(result, 3))


[[0.94  0.615 1.239 1.454]
 [0.745 0.405 0.747 1.099]
 [0.791 0.402 0.856 1.332]]


And with PyTorch

In [1]:
from numpy import matrix
import torch

# Create a random matrix
matrixM = torch.rand(3, 4)
matrixN = torch.rand(4, 4)

result = torch.mm(matrixM, matrixN)
print(np.round(result, 3))

# numpy and torch can be mixed for matrix operations
matrixI = matrixN.numpy()
print(np.round(matrixM @ matrixI, 3))


NameError: name 'np' is not defined